# Generated by Django 3.1.1 on 2020-09-13 09:55

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservoirs', '0002_auto_20200817_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('home_name', models.CharField(max_length=100)),
                ('number_of_residents', models.IntegerField()),
                ('home_owner_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservoir', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='reservoirs.reservoir')),
            ],
            options={
                'ordering': ['home_name'],
                'unique_together': {('reservoir', 'home_name')},
            },
        ),
        migrations.CreateModel(
            name='HomeWaterConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', month.models.MonthField(
                    help_text='Month Value', verbose_name='Month Value')),
                ('water_consumption', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='home_details.home')),
            ],
            options={
                'ordering': ['home', 'date'],
                'unique_together': {('home', 'date')},
            },
        ),
    ]
