# Generated by Django 3.1 on 2020-08-21 18:01

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservoirs', '0002_auto_20200817_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', month.models.MonthField(verbose_name='Year nan Month')),
                ('water_level', models.IntegerField()),
                ('water_consumption', models.IntegerField()),
                ('rainfall', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('evaporation', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservoirs.reservoir')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('reservoir', 'date')},
            },
        ),
    ]
