# Generated by Django 3.1.1 on 2020-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_level', '0002_auto_20200913_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterlevel',
            old_name='water_consumption',
            new_name='water_consumption_domestic',
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='water_consumption_paddy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
