# Generated by Django 3.1.1 on 2020-09-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_level', '0003_auto_20200922_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterlevel',
            name='water_consumption_domestic',
        ),
        migrations.RemoveField(
            model_name='waterlevel',
            name='water_consumption_paddy',
        ),
    ]
